name: bitsgap_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  intl_utils: ^2.8.2
  go_router: ^7.0.0
  flutter_simple_dependency_injection: ^2.0.0
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.4
  collection: ^1.17.0
  flutter_svg: ^2.0.5
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  flutter_gen_runner: ^5.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/


flutter_intl:
  enabled: true
  main_locale: en
  class_name: AppL10n
  arb_dir: lib/resources/l10n
  output_dir: lib/resources/l10n/generated

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true
  assets:
    enabled: true